# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: partner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'partner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpartner.proto\x12\x07partner\"\x1f\n\x11GetPartnerRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"Q\n\x12GetPartnerResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\x12\x11\n\ttenant_id\x18\x04 \x01(\t2W\n\x0ePartnerService\x12\x45\n\nGetPartner\x12\x1a.partner.GetPartnerRequest\x1a\x1b.partner.GetPartnerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'partner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPARTNERREQUEST']._serialized_start=26
  _globals['_GETPARTNERREQUEST']._serialized_end=57
  _globals['_GETPARTNERRESPONSE']._serialized_start=59
  _globals['_GETPARTNERRESPONSE']._serialized_end=140
  _globals['_PARTNERSERVICE']._serialized_start=142
  _globals['_PARTNERSERVICE']._serialized_end=229
# @@protoc_insertion_point(module_scope)
